### PR TITLE
Basic wan support

### PR DESCRIPTION
**Pull request by JalfResi**
Implemented basic WAN support - enough to get my local network working using PPPOE and my router in bridge mode on my USG. Everything works like a charm!

I will be adding to this over the coming weeks as I scale out my homelab - this was the key piece, now I know I can manage my WAN using terraform, I'll start to implement the other parts too (dns, etc)

### CODE REVIEW

**Comment by JalfResi** [comment]
Apologies - merge conflict with go.sum

**Comment by paultyng** [comment]
This looks good to me. I'm going to move the validation code in to the network file for now until its reused somewhere else.

 I am a little curious if it would be better to create resources by purpose, ie `unifi_network_wan`, `unifi_network_guest`, `unifi_network_corporate`, etc., but can always do that later if validation or other things get too unwieldy. Will merge this shortly, just had some other work I wanted to land on master real quick.

**Review by paultyng — APPROVED** [review]

**Comment by paultyng** [comment]
Oh, can you add an example file similar to the others for the docs (and then you can regenerate the docs using `go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs`).

**Comment by JalfResi** [comment]
Updated the examples and documentation as asked - had some issues pulling updates from upstream which resulted in the go.sum file becoming messed up again, so apologies - I would probably squash when merging this due to all the commit noise.

**Comment by paultyng** [comment]
No worries, will take a look today.

**Comment by paultyng** [comment]
I cleaned up the commits and sum stuff and some other things in #77, just waiting on a test pass before merging.

**Pull request closed without merging**
