### PR TITLE
Test 6.1 and 6.2 of the controller

### PR DESCRIPTION
**Pull request by paultyng**

### CODE REVIEW

**Comment by joshuaspence** [comment]
Do they have 6.1 and 6.2 tags or do we need to pin to a patch version?

**Review by joshuaspence — APPROVED** [review]

**Comment by paultyng** [comment]
I didn't see a 6.1 unfortunately, this was the best I could do.

**Comment by joshuaspence** [comment]
Was curious and checked myself, I think we should be able to use these:

- https://hub.docker.com/layers/jacobalberty/unifi/v6.2/images/sha256-07efb66b47b426e804b7958720dcf1c9e56882dccc54bc155f3f0de98fe71738?context=explore
- https://hub.docker.com/layers/jacobalberty/unifi/6.2/images/sha256-d03f5a1fca94a0afd69538bf7e5813e34e5113e6cefe772973b966168bb6ee4d?context=explore
- https://hub.docker.com/layers/jacobalberty/unifi/6.1/images/sha256-4215471e0ea79c727493da0310d541769032674c16f06b7f812b7f09c2a5633d?context=explore
- https://hub.docker.com/layers/jacobalberty/unifi/6.0/images/sha256-f7554a364b4b0b9e8d1c2100d4ae1a75d1c680eb98e1e66e0ac31184f377e94e?context=explore

**Comment by paultyng** [comment]
Ah good find, I was checking with the `v` prefix.

**Comment by paultyng** [comment]
Trying this in #165

**Pull request merged**
