### PR TITLE
Use `docker-compose` instead of a shell script

### PR DESCRIPTION
**Pull request by joshuaspence**

### CODE REVIEW

**Comment by paultyng** [comment]
@joshuaspence feel free to merge this when you are comfortable with it as long as its running the same tests I'm cool with it. I mostly dev on windows so I may need to make future changes as `make` isn't installed by default (not that bash is either 😭), but in general using docker compose is a lot easier. 👍🏻

**Comment by joshuaspence** [comment]
Sure, I hadn't merged it yet because you hadn't reviewed it yet :P Will rebase and retest in the morning.

**Comment by paultyng** [comment]
Yeah sorry I realized that was the case 😭

**Comment by joshuaspence** [comment]
@paultyng  GitHub won't let me merge the PR without review. I'm guessing that is a setting on the repo.

**Review by paultyng — APPROVED** [review]

**Pull request merged**
