### PR TITLE
Added support for destination port on the unifi_firewall_rule resource

### PR DESCRIPTION
**Pull request by andyalm**
I noticed this was missing and was using it on a couple of my rules. Let me know if I'm missing anything.

### CODE REVIEW

**Comment by paultyng** [comment]
This looks good to me, could you write a test for it?

**Comment by andyalm** [comment]
I'm happy to write a test, but could use a little direction in understanding how the current tests work. Is there an existing test where I could simply add a field verification assertion to? Or are you thinking a new test would be better?

**Comment by paultyng** [comment]
I think the best thing would be to copy/paste the [existing basic firewall rule test](https://github.com/paultyng/terraform-provider-unifi/blob/main/internal/provider/resource_firewall_rule_test.go), and add one with the destination port information. You do not need to add an assertion as long as you keep the "import step" as it makes Terraform do an apply, drop the state, re-import it via ID, and ensure the state doesn't cause a diff (essentially a full state assertion).

**Comment by andyalm** [comment]
Thanks for the direction. I've finally got around to adding the test. Let me know if there's anything else I can do.

**Review by paultyng — APPROVED** [review]

**Pull request merged**
