### PR TITLE
firewall_rule: Add enabled attribute

### LINKED ISSUE #62: firewall_rule: expose enabled attribute
Doesn't look like the firewall_rule resources allows setting Enabled to true/false.

### PR DESCRIPTION
**Pull request by chrishas35**
Resolves #62

Still need to do doc updates and maybe tests?  First time writing go, so feedback appreciated!

### CODE REVIEW

**Comment by paultyng** [comment]
I had added `enabled` on the `unifi_port_forward` but then decided to deprecate/remove it because I think its probably easier to just comment out or delete the code instead of managing this flag, but there are probably some use cases I'm not considering. Is there a reason to keep in port forwarding or firewall rules as disabled? Do you typically flip them on/off in the UI instead or something?

**Comment by chrishas35** [comment]
I do have a few rules that I keep disabled and flip on occasionally via the UI (mostly "accept anything"-type rules to let me back in). I'm okay with enabled being the default, but I do think it's helpful to have available for setting to false when desired. The alternative is not having such rules in TF, but that seems less than ideal since, at least for firewall rules, one has to manage the index without duplicates.

**Comment by paultyng** [comment]
Thats a good point about firewall rules and reserving indexes.

**Comment by paultyng** [comment]
This PR looks good otherwise, but you should add a test for a disabled rule to make sure it roundtrips appropriately.

The docs are generated, you can run `go run github.com/hashicorp/terraform-plugin-docs/cmd/tfpluginwebsite` to generate them from the root of the repo.

**Pull request merged**
