### PR TITLE
Add wlan_band field to wlan resource

### PR DESCRIPTION
**Pull request by kurtmc**
I see that the tests are failing for the v5 controller. I think I will need some help to resolve them.

### CODE REVIEW

**Review by paultyng — APPROVED** [review]

**Comment by paultyng** [comment]
Just rerunning tests, not sure why there were v5 failures since this should be skipped.

**Review by paultyng — CHANGES_REQUESTED** [review]
Ah, this is due to it having a default of "both", so if nothing is specified for v5, "both" comes through instead of "", resulting in a diff I think.

You could fix it up by removing the default, or suppressing the diff between "" and "both" probably.

**Comment by kurtmc** [comment]
Thanks for the help! By the way I ran `go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs` but there were a large number of differences, perhaps I have run the latest version? Anyway I just added the change related to my change.

**Review by paultyng — APPROVED** [review]

**Comment by paultyng** [comment]
hmm, unsure why that would be, i just use `go generate` now, unsure if it would work differently, it should be effectively the same based on the generation comments.

**Pull request merged**
