### PR TITLE
Create a Port Profile Resource and Data Source

### PR DESCRIPTION
**Pull request by jamestoyer**
Introduces a resource and data source for a port profile

### CODE REVIEW

**Comment by jamestoyer** [comment]
@paultyng I'm not sure why the tests are failing. They appear to be unrelated fails, but it could be something I did wrong

**Comment by jamestoyer** [comment]
Actually, it looks like I've just messed up things on the tests. I think I've fixed them now

**Comment by paultyng** [comment]
This looks good to me. Could you add a data source test and some examples for the generated docs?

**Comment by paultyng** [comment]
Sorry, I missed the data source test, so just the examples.

**Comment by jamestoyer** [comment]
@paultyng I think that should be everything now

**Review by paultyng — APPROVED** [review]
We may want to add some assertions to the data source test down the road, since it doesn't have the import assertion, but otherwise looks great, thanks!

**Pull request merged**
