### PR TITLE
add support for adding IPv6 to a network

### PR DESCRIPTION
**Pull request by ahanselka**
This adds the ability to add some IPv6 settings to a network. I wasn't quite sure how to do the tests here, totally open to feedback.

I was able to make this work with the following:

```
resource "unifi_network" "testnet-v6" {
  name    = "testnet-v6"
  purpose = "corporate"

  subnet       = "10.6.0.1/24"
  vlan_id      = "6"
  dhcp_start   = "10.6.0.200"
  dhcp_stop    = "10.6.0.250"
  dhcp_enabled = true
  dhcp_dns     = ["172.23.201.3"]

  ipv6_interface_type = "pd"
  ipv6_pd_interface   = "wan"
  ipv6_pd_prefixid    = "6"
  ipv6_ra_enable      = true
}
```

### CODE REVIEW

**Comment by ahanselka** [comment]
Hmm, not quite sure why the test is failing but worked for me. I suspect it is due to the fact that I already have IPv6 set up in the controller on my WAN interface.

**Comment by ahanselka** [comment]
I've thought a lot about this and tried today to set this up manually using the docker `controller.sh` that the tests use and I've been unsuccessful. I don't know that it is possible to set up prefix delegation without a working upstream DHCPv6-PD response. I can get it to set up a static IPv6 setup though. 

Thus, I changed the test to only test static IPv6 setups. Since we aren't testing with actual unifi hardware, I don't think we can somehow emulate a DHCPv6-PD situation.

**Comment by paultyng** [comment]
Thanks for the contribution / usage!

Are you able to test locally and just paste the results in? 

In other providers when there are testing limitations (ones depending on physical infrastructure we can't easily replicate, like a direct connect), commonly what we've done is skip the tests unless an environment variable is set, and just rely on users with the capability to test.

So assuming this is fully additive and you can pass a test run locally (and skip that test in the CI), open to merging here. I'll take a peek at the code later today or this weekend.

**Comment by ahanselka** [comment]
Sorry for the delay! I took a bit of a break from technology and it was quite nice ;)

I'm not quite sure how I could use the tests without breaking my current working config. I'm open to any suggestions you may have!

I have the following in my config, which yields a network like the screenshot.

```csv
name,purpose,subnet,vlan_id,ipv6_prefix_id,dhcp_start,dhcp_stop,domain_name
Guest WiFi,guest,10.2.0.1/24,2,2,10.2.0.50,10.2.0.200,<redacted domain>
```

```hcl
resource "unifi_network" "vlan" {
  for_each = local.vlans

  name    = each.key
  purpose = each.value.purpose

  subnet       = each.value.subnet
  vlan_id      = each.value.vlan_id != "" ? each.value.vlan_id : null
  dhcp_start   = each.value.dhcp_start
  dhcp_stop    = each.value.dhcp_stop
  dhcp_enabled = true
  dhcp_dns     = ["172.23.201.3"]
  domain_name  = each.value.domain_name

  ipv6_interface_type = "pd"
  ipv6_pd_interface   = "wan"
  ipv6_pd_prefixid    = each.value.ipv6_prefix_id != "" ? each.value.ipv6_prefix_id : null
  ipv6_ra_enable      = true
}
```

screencapture-unifi-hanselka-name-8443-manage-site-default-settings-networks-edit-595ab5d57e94f4536c7e00e4-2020-07-08-13_47_01

**Comment by paultyng** [comment]
Sorry for my delay as well, but this is available now: https://registry.terraform.io/providers/paultyng/unifi/latest/docs/resources/network

**Comment by paultyng** [comment]
Still missing a prefix delegation test, will need to try to add that later.

**Pull request closed without merging**
